import React from "react";
import { AccessGate } from "@/components/AccessGate";
import { startLogin } from "@/const";
import { useAuth } from "@/_core/hooks/useAuth";
import { trpc } from "@/lib/trpc";
import { AlertTriangle, CheckCircle2, Eye, FileArchive, Loader2, LockKeyhole, Mail, ShieldAlert, ShieldCheck } from "lucide-react";
import { Link } from "wouter";

type Surface = "campaigns" | "library" | "production" | "previews" | "audience";

const meta: Record<Surface, { eyebrow: string; title: string; description: string }> = {
  campaigns: { eyebrow: "Email OS · planning", title: "Campaigns & journeys", description: "The 53-email programme stays grouped by its canonical lifecycle series. A journey is not an authorization to activate it." },
  library: { eyebrow: "Email OS · source", title: "Email library", description: "Searchable source-backed inventory. Canonical copy remains verbatim and is never corrected in the interface." },
  production: { eyebrow: "Email OS · production", title: "Production queue", description: "The practical order of work, derived from canonical source status and evidence—not dates invented to populate a roadmap." },
  previews: { eyebrow: "Email OS · evidence", title: "Preview gallery", description: "Render evidence attaches to a source-backed revision and immutable package. No preview is simulated to fill an empty grid." },
  audience: { eyebrow: "Email OS · safety", title: "Audience & consent", description: "Consent remains a separate Shopify release gate. This workspace neither edits audiences nor permits broad-consent activation." },
};

function statusText(status: string) { return status === "ready" ? "Ready" : status === "needs_input" ? "Needs input" : "Source blocked"; }
function seriesCode(series: string) { return series.split("·")[0]?.trim() || series; }
function seriesName(series: string) { return series.split("·").slice(1).join("·").trim() || series; }

export default function EmailSurface({ surface }: { surface: Surface }) {
  const { isAuthenticated, loading } = useAuth();
  const portfolio = trpc.campaigns.portfolio.useQuery(undefined, { enabled: isAuthenticated });
  const page = meta[surface];
  if (loading) return <div className="page-loader"><Loader2 className="h-5 w-5 animate-spin" />Checking Marketing OS access…</div>;
  if (!isAuthenticated) return <AccessGate onSignIn={() => startLogin()} />;
  if (portfolio.isLoading) return <div className="page-loader"><Loader2 className="h-5 w-5 animate-spin" />Loading canonical Email OS evidence…</div>;
  if (portfolio.isError) return <div className="page-loader page-error"><AlertTriangle className="h-5 w-5" />{portfolio.error.message}</div>;
  const emails = portfolio.data ?? [];
  const ready = emails.filter(email => email.sourceStatus === "ready");
  const grouped = Array.from(new Map(emails.map(email => [email.series, emails.filter(item => item.series === email.series)])).entries());
  const rows = surface === "production" ? [...emails].sort((a, b) => Number(a.sourceStatus !== "ready") - Number(b.sourceStatus !== "ready")) : emails;
  const journeys = grouped.map(([series, items]) => ({ series, items, code: seriesCode(series), name: seriesName(series), ready: items.filter(item => item.sourceStatus === "ready").length }));
  const selectedJourney = journeys.find(journey => journey.code === "J2") ?? journeys[0];
  const selectedEmail = emails[0];
  const previewEvidence = emails.filter(email => email.latestRevision || email.latestHandoff).length;

  return <div className="marketing-page email-surface"><header className="page-heading marketing-heading"><div><p>{page.eyebrow}</p><h1>{page.title}</h1><span>{page.description}</span></div><Link href="/email/review" className="quiet-button"><ShieldCheck className="h-4 w-4" />Review &amp; QA</Link></header>
    {surface === "campaigns" && <>
      <section className="marketing-metrics"><article className="email-accent"><span>Campaigns & journeys</span><strong>{journeys.length}</strong><small>Lifecycle series derived from canonical records</small></article><article className="email-accent"><span>Canonical emails</span><strong>{emails.length}</strong><small>Native child records under their journeys</small></article><article><span>Source-ready records</span><strong>{ready.length}</strong><small>Canonical source authority is present</small></article><article className="risk"><span>Authorized activations</span><strong>0</strong><small>Owner action remains separate</small></article></section>
      <section className="journeys-v2-layout"><article className="journeys-v2-card"><div className="section-card-head"><div><h2>Journey portfolio</h2><p>Series status comes from canonical source evidence—not dates invented for a roadmap.</p></div><span className="state-pill">{ready.length} / {emails.length} source-ready</span></div><div className="journey-v2-head"><span>Code</span><span>Journey</span><span>Emails</span><span>Source</span><span>Stage</span><span>Next gate</span></div>{journeys.map(journey => <div className={`journey-v2-row ${journey.code === selectedJourney?.code ? "selected" : ""}`} key={journey.series}><code>{journey.code}</code><span><strong>{journey.name}</strong><small>Canonical Campaign issue</small></span><b>{journey.items.length}</b><i className={journey.ready === journey.items.length ? "evidence ready" : "evidence blocked"}>{journey.ready} / {journey.items.length}</i><span className="state-pill">{journey.ready === journey.items.length ? "In review" : "Blocked"}</span><span>{journey.ready === journey.items.length ? "Evidence + consent" : "Source authority"}</span></div>)}</article><aside className="journey-v2-detail"><div className="section-card-head"><div><p>Email journey</p><h2>{selectedJourney?.name ?? "No canonical journey"}</h2><span>{selectedJourney ? `${selectedJourney.items.length} canonical emails share this source-backed lifecycle family.` : ""}</span></div><span className="locked-chip">Activation locked</span></div>{selectedJourney && <><div className="journey-v2-meta"><div><span>Canonical emails</span><strong>{selectedJourney.items.length}</strong></div><div><span>Source-ready</span><strong>{selectedJourney.ready} / {selectedJourney.items.length}</strong></div><div><span>Activation</span><strong>Not authorized</strong></div></div><div className="journey-v2-sequence">{selectedJourney.items.slice(0, 5).map(email => <article key={email.key}><code>{email.key}</code><strong>{email.name.split("·").slice(1).join("·").trim()}</strong><small>{email.sourceStatus === "ready" ? "Source ready" : "Source blocked"}</small></article>)}</div><div className="journey-v2-gates"><div><CheckCircle2 className="h-4 w-4" /><span><strong>Canonical source family</strong><small>Series relationships are drawn from the canonical inventory.</small></span></div><div><ShieldCheck className="h-4 w-4" /><span><strong>Collision and purchase exits</strong><small>Journey mapping must be checked in the Shopify Flow review.</small></span></div><div><ShieldAlert className="h-4 w-4" /><span><strong>Audience, consent, and exclusions</strong><small>Eligibility requires current external evidence before any manual activation.</small></span></div><div><LockKeyhole className="h-4 w-4" /><span><strong>Activation and schedule</strong><small>No journey is authorized to activate or send here.</small></span></div></div></>}</aside></section>
    </>}
    {surface === "library" && <>
      <section className="marketing-metrics"><article className="email-accent"><span>Canonical emails</span><strong>{emails.length}</strong><small>Across lifecycle families and newsletter records</small></article><article><span>Source-ready</span><strong>{ready.length}</strong><small>Source authority is present</small></article><article className="email-accent"><span>Linked preview evidence</span><strong>{previewEvidence}</strong><small>Revision or manual handoff evidence exists</small></article><article className="risk"><span>Source blocked</span><strong>{emails.length - ready.length}</strong><small>Real source or mapping work remains</small></article></section>
      <section className="library-v2-layout"><article className="library-v2-card"><div className="section-card-head"><div><h2>Canonical email inventory</h2><p>The library exposes authority, source health, preview evidence, and operational stage without confusing any of them with release approval.</p></div><span className="state-pill">{emails.length} canonical records</span></div><div className="library-v2-head"><span>Email</span><span>Journey</span><span>Surface</span><span>Source</span><span>Preview</span><span>Stage</span></div>{emails.map(email => <Link key={email.key} href="/workspace" className="library-v2-row"><span><strong>{email.key} · {email.name.split("·").slice(1).join("·").trim()}</strong><small>{email.subject || "No canonical subject"}</small></span><code>{seriesCode(email.series)}</code><span>{email.shopifySurface}</span><i className={email.sourceStatus === "ready" ? "evidence ready" : "evidence blocked"}>{statusText(email.sourceStatus)}</i><i className={email.latestRevision || email.latestHandoff ? "evidence ready" : "evidence blocked"}>{email.latestHandoff ? "Draft evidence" : email.latestRevision ? "Revision saved" : "Not linked"}</i><span className="state-pill">{email.sourceStatus === "ready" ? "In review" : "Blocked"}</span></Link>)}</article><aside className="library-v2-detail"><div className="section-card-head"><div><p>Selected canonical record</p><h2>{selectedEmail ? `${selectedEmail.key} · ${selectedEmail.name.split("·").slice(1).join("·").trim()}` : "No record"}</h2><span>Canonical source record; Email release authorization remains absent.</span></div></div>{selectedEmail && <><div className="authority-chain"><div><b>01</b><span><strong>Email Reference File</strong><small>Copy and composition authority</small></span></div><div><b>02</b><span><strong>Canonical inventory</strong><small>Current operational read model</small></span></div><div><b>03</b><span><strong>Source status</strong><small>{statusText(selectedEmail.sourceStatus)}</small></span></div><div><b>04</b><span><strong>External release</strong><small>Not authorized</small></span></div></div><div className="library-v2-gates"><div><span>Source</span><strong>{selectedEmail.sourceStatus === "ready" ? "Source-ready" : "Blocked"}</strong></div><div><span>Preview evidence</span><strong>{selectedEmail.latestRevision || selectedEmail.latestHandoff ? "Linked evidence" : "Not linked"}</strong></div><div><span>Next gate</span><strong>{selectedEmail.sourceStatus === "ready" ? "QA review" : "Source authority"}</strong></div><div><span>External release</span><strong>Not authorized</strong></div></div><div className="library-rule"><Eye className="h-4 w-4" /><span><strong>Library rule</strong><small>A source record, revision, or rendered preview is never displayed as a send, activation, or live customer release.</small></span></div></>}</aside></section>
    </>}
    {surface === "production" && <section className="source-table"><div className="source-table-head"><span>Email</span><span>Journey</span><span>Platform</span><span>Source</span><span>Next gate</span></div>{rows.map(email => <Link key={email.key} href="/workspace" className="source-table-row"><span><strong>{email.key} · {email.name.split("·").slice(1).join("·").trim()}</strong><small>{email.subject || "No canonical subject"}</small></span><code>{email.series}</code><span>{email.shopifySurface}</span><i className={email.sourceStatus === "ready" ? "evidence ready" : "evidence blocked"}>{email.sourceStatus === "ready" ? <CheckCircle2 className="h-3.5 w-3.5" /> : <LockKeyhole className="h-3.5 w-3.5" />}{statusText(email.sourceStatus)}</i><span>{email.sourceStatus === "ready" ? "Review evidence" : "Source authority"}</span></Link>)}</section>}
    {surface === "previews" && <section className="surface-grid preview-gallery-grid">{emails.filter(email => email.latestRevision || email.latestHandoff).length ? emails.filter(email => email.latestRevision || email.latestHandoff).map(email => <article key={email.key} className="surface-card"><Eye className="h-5 w-5" /><code>{email.key}</code><h2>{email.name.split("·").slice(1).join("·").trim()}</h2><p>{email.latestHandoff ? "Shopify draft evidence recorded; release authority remains manual." : "Revision saved; screenshot evidence has not been linked to a package."}</p><Link href="/workspace">Open evidence</Link></article>) : <article className="empty-evidence"><FileArchive className="h-7 w-7" /><h2>No immutable preview package yet.</h2><p>Preview screenshots appear only after a source-backed revision, deterministic QA, and an export package exist. This intentional empty state prevents fictional render evidence.</p><Link href="/email/review">Open the review queue</Link></article>}</section>}
    {surface === "audience" && <section className="surface-grid audience-grid"><article className="surface-card consent-card"><ShieldCheck className="h-5 w-5" /><h2>Consent is a release gate</h2><p>Canonical source readiness is not audience authorization. Consent must be re-verified in Shopify for the specific channel before a human activates any journey.</p><i className="locked-chip">No audience mutation authority</i></article><article className="surface-card consent-card"><LockKeyhole className="h-5 w-5" /><h2>Broad consent remains blocked</h2><p>This application does not surface a broad-subscriber activation control. Approved cohort details live in controlled platform evidence, not in a local UI toggle.</p><i className="locked-chip">Activation locked</i></article><article className="surface-card consent-card"><Mail className="h-5 w-5" /><h2>Newsletter frequency cap</h2><p>Lifecycle collisions, purchase exits, sunset suppression, and frequency rules remain Flow/Messaging review requirements.</p><Link href="/email/flow">Open Messaging &amp; Flow</Link></article></section>}
  </div>;
}
