import React from "react";
import { AccessGate } from "@/components/AccessGate";
import { startLogin } from "@/const";
import { useAuth } from "@/_core/hooks/useAuth";
import { trpc } from "@/lib/trpc";
import { AlertTriangle, BadgeCheck, CheckCircle2, FileQuestion, FolderLock, Lightbulb, Loader2, LockKeyhole, ShieldAlert, ShieldCheck } from "lucide-react";

type GovernanceKind = "decisions" | "assets" | "insights";

const surfaceCopy: Record<GovernanceKind, { eyebrow: string; title: string; description: string }> = {
  decisions: { eyebrow: "Email OS · governance", title: "Approvals & Decisions", description: "A single review inbox for Email decisions that unblock source-backed work. Recording a decision never sends, schedules, activates, or changes an audience." },
  assets: { eyebrow: "Email OS · governance registry", title: "Assets, Claims & Rights", description: "One linked registry for Email media identity, permitted use, product and outcome claims, consent, copyright, and expiry. Missing evidence remains blocked." },
  insights: { eyebrow: "Email OS · institutional memory", title: "Insights & Learnings", description: "Source-backed Email findings, evidence maturity, and reusable decisions are separated from customer-performance claims until valid measurement evidence exists." },
};

function GateIcon({ status }: { status: "done" | "pending" | "blocked" }) {
  const Icon = status === "done" ? CheckCircle2 : status === "blocked" ? LockKeyhole : ShieldAlert;
  return <span className={`governance-gate-icon ${status}`}><Icon className="h-3.5 w-3.5" /></span>;
}

export default function GovernanceSurface({ kind }: { kind: GovernanceKind }) {
  const { isAuthenticated, loading } = useAuth();
  const portfolio = trpc.campaigns.portfolio.useQuery(undefined, { enabled: isAuthenticated });
  const page = surfaceCopy[kind];
  if (loading) return <div className="page-loader"><Loader2 className="h-5 w-5 animate-spin" />Checking Marketing OS access…</div>;
  if (!isAuthenticated) return <AccessGate onSignIn={() => startLogin()} />;
  if (portfolio.isLoading) return <div className="page-loader"><Loader2 className="h-5 w-5 animate-spin" />Loading Email evidence…</div>;
  if (portfolio.isError) return <div className="page-loader page-error"><AlertTriangle className="h-5 w-5" />{portfolio.error.message}</div>;

  const emails = portfolio.data ?? [];
  const ready = emails.filter(email => email.sourceStatus === "ready").length;
  const blocked = emails.length - ready;

  return <div className="marketing-page governance-page"><header className="page-heading marketing-heading"><div><p>{page.eyebrow}</p><h1>{page.title}</h1><span>{page.description}</span></div><span className="readonly-pill"><ShieldCheck className="h-3.5 w-3.5" />Read-only</span></header>
    {kind === "decisions" && <>
      <section className="marketing-metrics"><article><span>Open governance gates</span><strong>4</strong><small>Evidence decisions, not execution requests</small></article><article className="email-accent"><span>Email source blockers</span><strong>{blocked}</strong><small>Canonical gaps remain visible</small></article><article className="risk"><span>Authorized releases</span><strong>0</strong><small>No Email send is authorized here</small></article><article><span>Execution boundaries</span><strong>Locked</strong><small>Shopify action stays manual</small></article></section>
      <section className="governance-split"><article className="governance-card"><div className="section-card-head"><div><h2>Owner decision inbox</h2><p>Only email decisions that need explicit human judgment appear here.</p></div><span className="state-pill">Evidence first</span></div><div className="governance-list"><div><b>01</b><div><strong>Reverify Email consent before any activation</strong><span>Audience eligibility is a distinct Shopify release gate.</span></div><i className="locked-chip">Required</i></div><div><b>02</b><div><strong>Resolve canonical source and real-data dependencies</strong><span>{blocked} Email records remain blocked or need input.</span></div><i className="warning-chip">Open</i></div><div><b>03</b><div><strong>Confirm Flow collision, purchase-exit, and frequency rules</strong><span>Journey relationship evidence remains separate from campaign copy.</span></div><i className="warning-chip">Review</i></div><div><b>04</b><div><strong>Authorize manual Shopify release review</strong><span>Any release decision remains manual and outside this application.</span></div><i className="locked-chip">Not authorized</i></div></div></article><article className="governance-card decision-detail"><div className="section-card-head"><div><h2>Decision boundary</h2><p>Consent re-verification scope</p></div><span className="surface-chip">Email OS</span></div><div className="decision-detail-body"><h3>What evidence is required before an Email release review?</h3><p>The reviewer needs current Shopify consent evidence for the intended cohort, exclusions, and human read-back. This application intentionally cannot select or alter that audience.</p><div className="decision-options"><div><GateIcon status="pending" /><span><strong>Use current, source-backed consent evidence</strong><small>Recommendation only; it does not authorize sending.</small></span></div><div><GateIcon status="pending" /><span><strong>Require a narrower documented cohort</strong><small>Escalate if consent or exclusions cannot be verified.</small></span></div><div><GateIcon status="blocked" /><span><strong>Hold Email activation work</strong><small>Keep canonical and preview work separate while eligibility is unresolved.</small></span></div></div></div></article></section>
    </>}
    {kind === "assets" && <>
      <section className="marketing-metrics"><article><span>Production Email assets</span><strong>0</strong><small>No rights-approved Email asset registry record</small></article><article><span>Reference candidates</span><strong>0</strong><small>Evidence must be linked before use</small></article><article className="risk"><span>Claims requiring review</span><strong>0</strong><small>No unverified claim becomes production copy</small></article><article className="risk"><span>Rights blocked</span><strong>0</strong><small>Missing evidence is not treated as clearance</small></article></section>
      <section className="governance-split"><article className="governance-card"><div className="section-card-head"><div><h2>Governance registry</h2><p>Email asset, claim, and rights evidence becomes visible only when a linked source record exists.</p></div><span className="locked-chip">No approved records</span></div><div className="empty-registry"><FolderLock className="h-7 w-7" /><h2>No governed Email asset records are linked.</h2><p>This intentionally empty registry will not manufacture a media item, customer quote, consent, copyright owner, claim, or expiry date merely to populate a table.</p></div></article><article className="governance-card asset-detail"><div className="section-card-head"><div><h2>Evidence rule</h2><p>Fail closed</p></div><span className="locked-chip">Blocked without proof</span></div><div className="asset-evidence"><FileQuestion className="h-8 w-8" /><strong>Visual availability is not permitted use.</strong><span>Before an Email asset or claim can appear in a release package, its source, provider identity, usage scope, rights/consent, and review outcome must be attached as evidence.</span><div><GateIcon status="blocked" /><p>Customer consent and right-to-use evidence</p></div><div><GateIcon status="blocked" /><p>Source, exact copy/claim wording, and provenance</p></div><div><GateIcon status="blocked" /><p>Expiry, channel scope, and withdrawal conditions</p></div></div></article></section>
    </>}
    {kind === "insights" && <>
      <section className="marketing-metrics"><article className="risk"><span>Live Email results</span><strong>0</strong><small>No approved sends or measurement evidence</small></article><article className="email-accent"><span>Source-ready records</span><strong>{ready}</strong><small>Canonical source evidence is present</small></article><article><span>Blocked records</span><strong>{blocked}</strong><small>Source and mapping gaps remain open</small></article><article><span>Reuse candidates</span><strong>0</strong><small>No performance-proven reuse decision</small></article></section>
      <section className="governance-split insights-split"><article className="governance-card"><div className="section-card-head"><div><h2>Learning ledger</h2><p>Findings are durable only when their evidence and implication are explicit.</p></div><span className="state-pill">Operational evidence</span></div><div className="learning-table"><div className="learning-head"><span>Finding</span><span>Verified fact</span><span>Evidence</span><span>Implication</span></div><div><span><strong>Email source readiness</strong><small>Canonical inventory</small></span><span>{ready} of {emails.length} records are source-ready</span><i className="evidence ready"><BadgeCheck className="h-3.5 w-3.5" />SOURCE</i><span>Resolve the remaining source and Shopify-variable gaps without weakening the renderer.</span></div><div><span><strong>Blocked Email sources</strong><small>Canonical inventory</small></span><span>{blocked} records remain intentionally blocked</span><i className="evidence blocked"><LockKeyhole className="h-3.5 w-3.5" />SOURCE</i><span>Treat blocks as authoring or mapping work, not a cosmetic preview problem.</span></div><div><span><strong>Release and measurement</strong><small>Email OS</small></span><span>No marketing send is authorized</span><i className="evidence blocked"><LockKeyhole className="h-3.5 w-3.5" />AUTHORITY</i><span>Customer-performance attribution is unavailable until a valid release and data read-back exist.</span></div></div></article><article className="governance-card evidence-ladder"><div className="section-card-head"><div><h2>Evidence maturity</h2><p>“Done” means different things at each level.</p></div></div><div><b>01</b><span><strong>Authority</strong><small>Governed source and owner decision inspected.</small></span><i>Strong</i></div><div><b>02</b><span><strong>Source</strong><small>Canonical Email representation inspected.</small></span><i>Strong</i></div><div><b>03</b><span><strong>Local validated</strong><small>Build, schema, and deterministic tests passed locally.</small></span><i>Partial</i></div><div><b>04</b><span><strong>Platform draft verified</strong><small>Exact rendered draft read back by a human.</small></span><i>Limited</i></div><div><b>05</b><span><strong>Live release verified</strong><small>Customer-facing release independently read back.</small></span><i>None</i></div><div className="measurement-boundary"><Lightbulb className="h-4 w-4" /><span><strong>Measurement boundary</strong><small>No conversion, revenue, engagement, or customer-performance learning is represented until live evidence exists.</small></span></div></article></section>
    </>}
  </div>;
}
